#!/bin/bash

sudo apt-get update 
sudo apt upgrade -y
sudo apt dist-upgrade -y
sudo apt autoremove -y

sudo apt-get install openjdk-11-jdk -y
sudo apt-get install g++ -y
sudo apt-get install python3 -y

sudo apt-get install code -y
sudo snap install sublime-text -y

sudo apt-get install firefox -y
sudo apt-get install telegram-desktop -y
sudo apt-get install gnome-tweaks -y
sudo apt-get install vlc -y

sudo apt-get install guake -y

cd
git clone https://github.com/Circles24/HandyScripts.git

cd HandyScripts
chmod +x CP
sudo mv CP /usr/bin/CP

cd
git clone https://github.com/Circles24/CompetitiveProgramming.git
mkdir compy
cat CompetitiveProgramming > compy/temp.cpp
touch compy/compy.cpp




